# Description.
model_template_id: Custom_Image_Classification_MobileNet-V3-large-1x
name: MobileNet-V3-large-1x
task_type: CLASSIFICATION
task_family: VISION
instantiation: "CLASS"
summary: Custom Image Classification MobileNet-V3-large-1x
application:
  ~

# Algo backend.
framework: OTEClassification v1.2.3

# Task implementations.
entrypoints:
  base: torchreid.integration.sc.task.OTEClassificationTask
  openvino: torchreid.integration.sc.openvino_task.OpenVINOClassificationTask

# Capabilities.
capabilities:
  - compute_representations
  - compute_uncertainty_score

# Hyperparameters.
hyper_parameters:
  base_path: "../../../torchreid/integration/sc/configuration.yaml"
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 64
      max_num_epochs:
        default_value: 200
      learning_rate:
        default_value: 0.005

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 0.44
size: 4.29
