lr_finder:
  enable: False
  mode: TPE
  stop_after: False
  num_epochs: 10
  step: 1e-5
  epochs_warmup: 1
  path_to_savefig: 'lr_finder.jpg'
  max_lr: 1e-3
  min_lr: 1e-5
  n_trials: 15

model:
  name: 'mld_efficientnetv2_s_21k'
  type: 'multilabel'
  pretrained: True
  load_weights:
  save_all_chkpts: False
  dropout_cls:
    p: 0.1

custom_datasets:
  roots: ['./datasets/COCO/train.json', './datasets/COCO/val.json']
  types: ['multilabel_classification', 'multilabel_classification']

data:
  root: './'
  height: 448
  width: 448
  norm_mean: [0.5, 0.5, 0.5]
  norm_std: [0.5, 0.5, 0.5]
  save_dir: 'output/efficientnetv2_s_21k/COCO'
  workers: 6
  transforms:
    random_flip:
      enable: True
      p: 0.5
    randaugment:
      enable: True
    cutout:
      enable: True
      cutout_factor: 0.4
      p: 0.5

loss:
  name: 'am_binary'
  softmax:
    s: 23.0
    m: 0.0
    compute_s: False
  asl:
    gamma_pos: 0.
    gamma_neg: 0.
  am_binary:
    amb_k: 0.7


sampler:
  train_sampler: 'RandomSampler'

train:
  optim: 'sam'
  lr: 0.007
  nbd: True
  max_epoch: 60
  weight_decay: 5e-4
  batch_size: 84
  lr_scheduler: 'onecycle'
  early_stopping: True
  pct_start: 0.2
  train_patience: 5
  lr_decay_factor: 1000
  deterministic: True
  target_metric: test_acc
  gamma: 0.1
  sam:
    rho: 0.05
  ema:
    enable: True
    ema_decay: 0.9997
  mix_precision: True

test:
  batch_size: 128
  evaluate: False
  eval_freq: 1
